# Generated by Django 5.2.3 on 2025-06-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='heroin',
            new_name='heroine',
        ),
    ]
