# Generated by Django 4.1 on 2025-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsapp', '0002_hydjobs_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
