# Generated by Django 4.1 on 2025-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobsapp', '0004_bangjobs_punejobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangjobs',
            name='company',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bangjobs',
            name='eligibility',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bangjobs',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='company',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
