# Generated by Django 4.1 on 2025-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_employee_eno_alter_employee_esal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esal',
            field=models.FloatField(),
        ),
    ]
